import { Link } from "@tanstack/react-router";
import { ArrowRight, Bell, Check, CircleDot, LayoutDashboard, PlugZap, Rocket, Sparkles, Users } from "lucide-react";
import { Button } from "./ui/button";

export function DashboardPreview({ compact = false }: { compact?: boolean }) {
  const bars = [38,55,46,68,61,78,70,86,82,94,88,100];
  return <div className="overflow-hidden rounded-2xl bg-card text-foreground shadow-2xl ring-1 ring-foreground/10">
    <div className="flex h-11 items-center gap-2 border-b border-border bg-muted/50 px-4"><i className="size-2.5 rounded-full bg-foreground/15"/><i className="size-2.5 rounded-full bg-foreground/15"/><i className="size-2.5 rounded-full bg-foreground/15"/><span className="ml-2 truncate font-mono text-[10px] text-muted-foreground">app.nexus.io/operations</span></div>
    <div className="grid sm:grid-cols-[180px_1fr]">
      <aside className="hidden border-r border-border bg-muted/35 p-4 sm:block"><div className="flex items-center gap-2 font-display text-sm font-semibold"><span className="grid size-6 place-items-center rounded bg-primary text-[10px] text-primary-foreground">N</span>Nexus</div><div className="mt-5 space-y-1 text-xs text-muted-foreground">{["Overview","Projects","Automations","Integrations","Team"].map((x,i)=><div key={x} className={`rounded-md px-3 py-2 ${i===0?"bg-primary/10 text-primary":""}`}>{x}</div>)}</div></aside>
      <div className={compact ? "p-4" : "p-4 md:p-6"}><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-2"><div className="min-w-0"><p className="truncate font-mono text-[10px] uppercase text-muted-foreground">Q4 · Operations overview</p><h3 className="truncate text-xl font-semibold">Good morning, Priya</h3></div><span className="hidden rounded-full bg-primary/10 px-3 py-1 font-mono text-[10px] text-primary md:block">Live · 1,284/min</span></div>
        <div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{[["Projects","42","+6 this week"],["Automations","18.2k","99.8% success"],["Integrations","27","+3 connected"],["On time","94%","+2.1 pts"]].map(([a,b,c])=><div key={a} className="rounded-lg border border-border p-3"><p className="text-[10px] text-muted-foreground">{a}</p><p className="font-display text-xl font-semibold">{b}</p><p className="text-[10px] text-primary">{c}</p></div>)}</div>
        <div className="mt-3 grid gap-3 lg:grid-cols-[1fr_240px]"><div className="rounded-lg border border-border p-3"><p className="font-mono text-[9px] uppercase text-muted-foreground">Throughput · 12 weeks</p><div className="mt-4 flex h-24 items-end gap-1.5">{bars.map((h,i)=><i key={i} className="flex-1 rounded-t bg-primary" style={{height:`${h}%`,opacity:.18+i*.065}}/>)}</div></div><div className="rounded-lg border border-border p-3"><p className="font-mono text-[9px] uppercase text-muted-foreground">Live operations</p><div className="mt-3 space-y-3 text-xs">{["Deploy pipeline","CRM sync","Invoice flow","Digest"].map((x,i)=><div key={x} className="flex justify-between gap-2"><span className="truncate text-muted-foreground">{x}</span><span className="font-mono text-[9px] text-primary">{i===3?"sent":"running"}</span></div>)}</div></div></div>
      </div>
    </div>
  </div>;
}

export const featureData = [
  {icon: LayoutDashboard,title:"Live analytics",text:"See project health, revenue, capacity, and risk from one continuously updated view."},
  {icon: Rocket,title:"Visual automations",text:"Build dependable workflows across teams and tools without maintaining fragile scripts."},
  {icon: Users,title:"Team operations",text:"Keep ownership, approvals, conversations, and delivery context beside the work."},
  {icon: PlugZap,title:"Connected stack",text:"Sync more than 120 products with two-way data and precise field mapping."},
];

export function FeatureGrid(){return <div className="grid gap-3 md:grid-cols-2">{featureData.map(({icon:Icon,title,text},i)=><article key={title} className={`${i===0?"md:col-span-2":""} group rounded-xl border border-border bg-card p-6 transition hover:-translate-y-1 hover:shadow-lg`}><Icon className="size-5 text-primary"/><h3 className="mt-6 text-xl font-semibold">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">{text}</p></article>)}</div>}

export function PageHero({eyebrow,title,description,children}: {eyebrow:string;title:string;description:string;children?:React.ReactNode}) { return <section className="border-b border-border bg-card"><div className="page-shell section-pad"><p className="font-mono text-[11px] uppercase text-primary">{eyebrow}</p><h1 className="mt-4 max-w-4xl text-4xl font-semibold leading-[1.02] sm:text-6xl">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{description}</p>{children&&<div className="mt-8">{children}</div>}</div></section> }

export function CTA(){return <section className="page-shell section-pad"><div className="grid-surface overflow-hidden rounded-2xl bg-foreground px-6 py-14 text-center text-background sm:px-10"><Sparkles className="mx-auto size-6 text-primary"/><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-semibold sm:text-5xl">Put your operation on one clear signal.</h2><p className="mx-auto mt-4 max-w-lg text-background/60">Start in minutes. Bring your current stack. Cancel whenever you like.</p><div className="mt-7 flex flex-wrap justify-center gap-3"><Button asChild size="xl"><Link to="/signup">Start free <ArrowRight/></Link></Button><Button asChild variant="heroOutline" size="xl"><Link to="/contact">Talk to sales</Link></Button></div></div></section>}

export function Steps(){return <div className="grid gap-3 md:grid-cols-4">{[["01","Connect","Bring in the tools and data you already use."],["02","Model","Shape projects, metrics, and ownership."],["03","Automate","Turn repeatable work into reliable flows."],["04","Improve","Measure results and tune every cycle."]].map(([n,t,d])=><div key={n} className="border-t border-primary pt-5"><span className="font-mono text-xs text-primary">{n}</span><h3 className="mt-8 text-lg font-semibold">{t}</h3><p className="mt-2 text-sm text-muted-foreground">{d}</p></div>)}</div>}

export function TrustStrip(){return <div className="overflow-hidden border-y border-border bg-card py-5"><div className="marquee-track flex w-max gap-14 pr-14 font-display text-sm font-semibold uppercase text-muted-foreground"><span>Northwind</span><span>Cobalt Labs</span><span>Meridian</span><span>Foundry</span><span>Aster & Co</span><span>Helio</span><span>Northwind</span><span>Cobalt Labs</span><span>Meridian</span><span>Foundry</span><span>Aster & Co</span><span>Helio</span></div></div>}

export function IntegrationGrid(){const apps=["Slack","GitHub","Stripe","HubSpot","Figma","Notion","Linear","Jira","Salesforce","Teams","Zapier","+108"];return <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{apps.map((a,i)=><div key={a} className="group grid min-h-28 place-items-center rounded-xl border border-border bg-card font-display font-semibold transition hover:border-primary hover:text-primary"><span className="grid size-11 place-items-center rounded-lg bg-primary/10 text-sm text-primary">{i<11?a.slice(0,2):a}</span><span>{a}</span></div>)}</div>}

export function PricingCards(){return <div className="grid gap-4 lg:grid-cols-3">{[{n:"Starter",p:"$0",d:"For small teams building a clear operating rhythm.",f:["5 seats","Core projects","5 integrations"]},{n:"Growth",p:"$24",d:"For teams automating work and scaling visibility.",f:["Unlimited projects","Advanced analytics","Priority support"],hot:true},{n:"Scale",p:"Custom",d:"For organizations with advanced security and control.",f:["SSO & audit logs","Data residency","Dedicated success"]}].map(x=><article key={x.n} className={`rounded-xl border p-7 ${x.hot?"border-primary bg-foreground text-background":"border-border bg-card"}`}><div className="flex justify-between"><h3 className="text-lg font-semibold">{x.n}</h3>{x.hot&&<span className="font-mono text-[10px] uppercase text-primary">Most popular</span>}</div><p className="mt-6 font-display text-4xl font-semibold">{x.p}</p><p className={`mt-3 min-h-12 text-sm ${x.hot?"text-background/60":"text-muted-foreground"}`}>{x.d}</p><ul className="my-7 space-y-3 text-sm">{x.f.map(f=><li key={f} className="flex gap-2"><Check className="size-4 text-primary"/>{f}</li>)}</ul><Button className="w-full" variant={x.hot?"default":"outline"} asChild><Link to="/signup">Choose {x.n}</Link></Button></article>)}</div>}

export function MiniStats(){return <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["42","Active projects"],["18.2k","Monthly runs"],["94%","On-time delivery"],["3.7h","Saved per person"]].map(([v,l])=><div key={l} className="rounded-xl border border-border bg-card p-5"><CircleDot className="size-4 text-primary"/><strong className="mt-6 block font-display text-3xl">{v}</strong><span className="text-xs text-muted-foreground">{l}</span></div>)}</div>}